### ISSUE TITLE
Segfault in logErr

### ISSUE THREAD

**Issue by PeukerP** [LageTs/goTrack#1]
After successful execution of the command in the worst case, I encountered a segfault in `logErr()` due to a missing nil check in `exec()`:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x517646]

goroutine 1 [running]:
main.Config.logErr({0x1, {0xc000018180, 0x11}, 0x3, 0x3e8, {0xc000014710, 0x10}, 0x1, {0xc0000202f0, 0x1, ...}, ...}, ...)
	/tmp/goTrack/config.go:106 +0x26
main.Config.exec({0x1, {0xc000018180, 0x11}, 0x3, 0x3e8, {0xc000014710, 0x10}, 0x1, {0xc0000202f0, 0x1, ...}, ...}, ...)
	/tmp/goTrack/config.go:98 +0x4e8
main.(*USBTracker).TrackUSBDevices(0xc000025c10, 0x0, 0x0)
	/tmp/goTrack/usb.go:91 +0x5b1
main.main()
	/tmp/goTrack/main.go:154 +0xed8
```
Steps to reproduce:
- `./goTrack -p goTrack.yaml`
-  Plug in a USB device. Also fails with unplugging.

My goTrack.yaml:
```
# Config for goTrack. Shall be placed in /etc/ as goTrack.yaml
# Shall the file lock be used? If activated commands will only be executed if the file exists. File will be created at launch.
fileLock: true
# File to be checked for file lock
fileLockPath: "/tmp/goTrack.lock"
# Delay until start in seconds
startDelay: 3
# Interval between checks in milliseconds
interval: 1000
# Log file path - print if not existing
logFile: "/tmp/goTrack.log"
# Number of old log files to keep: 1 keeps current and last, 0 keeps current
oldLogs: 1
# IDs to be ignored
ignoredIDs:
  - "Test"
# Enable usb checking
usb_tracking: true
# Commands to be executed
commands:
  - command: "ls" # Command
    args: # Arguments as strings
      - "-la"
    late: true # Set true to execute commands after others
    usb: true # Set true to execute command on usb changes
```
